# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &store3
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: store3MSP

        # ID to load the MSP definition as
        ID: store3MSP

        MSPDir: ../organizations/peerOrganizations/store3.nusayer.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('store3MSP.admin', 'store3MSP.peer', 'store3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('store3MSP.admin', 'store3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('store3MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('store3MSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.store3.nusayer.com
              Port: 11051
